/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rainqin_china' at '16-6-2 上午8:32' with Gradle 2.14-rc-2
 *
 * @author rainqin_china, @date 16-6-2 上午8:32
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
